[required]
pseudo_dir = "/home/username/PseudoPotentials"
pp_file = "/home/username/mcif2qewan/pp_psl_pbe_rrkjus.csv"

[optional]
use_symwan = true
#use_ibrav = true

[pw_control.scf]
tstress = ".true."
tprnfor = ".true."

[pw_control.nscf]
tstress = ".true."
tprnfor = ".true."

[pw_system.scf]
nspin = 2

[pw_system.nscf]

[pw_electrons.scf]

[pw_electrons.nscf]

[pw2wan]

[wannier]

[bands]
